config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :forms
  devise_scope :user do
    authenticated :user do
      root 'forms#index', as: :authenticated_root
    end
    unauthenticated do
      root 'forms#new', as: :unauthenticated_root
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dme_contact.rb
class DmeContact < ApplicationRecord
  belongs_to :form, dependent: :destroy
  # validates_format_of :phone, :with => /\d{3}-\d{3}-\d{4}/, :allow_blank => true
  # validates_format_of :zip, :with => %r{\d{5}(-\d{4})?}, :allow_blank => true
end

app/models/form.rb
class Form < ApplicationRecord
  require 'uri'

  has_many :form_products, inverse_of: :form, :dependent => :delete_all
  has_many :products, through: :form_products, :dependent => :delete_all
  accepts_nested_attributes_for :form_products

  has_many :surgeon_contacts, inverse_of: :form, :dependent => :delete_all
  accepts_nested_attributes_for :surgeon_contacts

  has_many :dme_contacts, inverse_of: :form, :dependent => :delete_all
  accepts_nested_attributes_for :dme_contacts

  has_many :pt_contacts, inverse_of: :form, :dependent => :delete_all
  accepts_nested_attributes_for :pt_contacts

  validates :region, presence: true
  validates :signature, presence: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }

end

app/models/form_product.rb
class FormProduct < ApplicationRecord
  belongs_to :form
  belongs_to :product
  accepts_nested_attributes_for :product
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :form_products
  has_many :forms, through: :form_products
end

app/models/pt_contact.rb
class PtContact < ApplicationRecord
  belongs_to :form, dependent: :destroy
  # validates_format_of :phone, :with => /\d{3}-\d{3}-\d{4}/, :allow_blank => true
  # validates_format_of :zip, :with => %r{\d{5}(-\d{4})?}, :allow_blank => true
end

app/models/surgeon_contact.rb
class SurgeonContact < ApplicationRecord
  belongs_to :form, dependent: :destroy
  # validates_format_of :phone, :with => /\d{3}-\d{3}-\d{4}/, :allow_blank => true
  # validates_format_of :zip, :with => %r{\d{5}(-\d{4})?}, :allow_blank => true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  before_action :authenticate_user!, except: [:new]
  before_action :set_form, only: [:show, :edit, :update, :destroy]

  def index
    @forms = Form.all
  end

  def new
    @products = Product.all
    @form = Form.new
    @products.each{ |product| @form.form_products.build(form: @form, product: product) }
    1.times { @form.surgeon_contacts.build }
    5.times { @form.dme_contacts.build }
    5.times { @form.pt_contacts.build }
  end

  def create
    @form = Form.new(form_params)
    form_params[:form_products_attributes].each do |attribute|
      @form.form_products.new(product: Product.find(attribute[1][:product_id]))
    end
    @form.save!
    # Tell the UserMailer to send a welcome email after save
    FormMailer.with(reciepient: @form.email, form: @form).welcome_email.deliver
    redirect_to @form
  end

  def show
    @form = Form.find(params[:id])
  end

  def edit
    @products = Product.all
  end

  def update
    @form.update(form_params)
    redirect_to forms_path
  end

  def destroy
    @form.surgeon_contacts.destroy_all
    @form.dme_contacts.destroy_all
    @form.pt_contacts.destroy_all
    @form.destroy
    redirect_to forms_path
  end

  private

  def set_form
    @form = Form.find(params[:id])
  end

  def form_params
    params.require(:form).permit(
      :email,
      :region,
      :joint_replacement,
      :sports_medicine,
      :orthopedic_trauma,
      :non_surgical_orthopedic,
      :spine,
      :other_conditions,
      :substitutions,
      :signature,
      :date,
      surgeon_contacts_attributes: [
        :name,
        :primary,
        :phone,
        :street,
        :city,
        :state,
        :zip,
      ],
      dme_contacts_attributes: [
        :name,
        :primary,
        :phone,
        :street,
        :city,
        :state,
        :zip,
      ],
      pt_contacts_attributes: [
        :name,
        :primary,
        :phone,
        :street,
        :city,
        :state,
        :zip,
      ],
      form_products_attributes: [
        :amount,
        :product_id,
      ]
    )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forms_helper.rb
module FormsHelper
end

app/views/forms/_form.html.erb
<%= form_with(model: form, local: true) do |f| %>

  <div id="page-1">
      <div class="instructions">
        <p><strong> This form must be filled out completely - TYPE or PRINT information below:</strong> </p>
      </div>
      <div class="section">
          <div class="blue">
          <p>SURGEON INFORMATION</p>
          </div>
          <%= f.fields_for :surgeon_contacts do |surgeon_form| %>
            <div class="field">
              <%= surgeon_form.label "Name:" %>
              <%= surgeon_form.text_field :name, class: 'form-control' %>
            </div>
            <div class="field">
              <%= surgeon_form.label "Address:" %>
              <%= surgeon_form.text_field :street, class: 'form-control'  %>
            </div>
            <div>
              <p class="grey">Daytime Contact Information</p>
            </div>
            <div class="field">
              <%= surgeon_form.label "Phone:" %>
              <%= surgeon_form.text_field :phone, class: 'form-control' %>
            </div>
            <div class="field">
              <%= surgeon_form.label "Contact Person:" %>
              <%= surgeon_form.text_field :primary, class: 'form-control' %>
            </div>
          <% end %>
          <div class="blue region">
            <p>REGION</p>
          </div>
            <div class="field">
              <%= f.radio_button :region, "East" %>
              <%= f.label "East", class:"radio" %>
            </div>
            <div class="field">
              <%= f.radio_button :region, "West" %>
              <%= f.label "West", class:"radio" %>
            </div>
        </div>
        <div id="regions">
          <%= image_tag 'https://i.imgur.com/EatbRWY.png', id: 'regions-image' %>
        </div>
  </div>


  <div id="page-2">
    <div class="page-header">
      <h5>ORDER INFORMATION</h5>
      <div class="instructions">
        <p><strong>TYPE or PRINT where the prescriptions are to be delivered</strong></p>
      </div>
    </div>
      <div class="section">
        <div id="page-2-1">
            <div class="blue">
              <p>HOSPITAL/DME AND PHYSICAL THERAPY INFORMATION</p>
            </div>
            <div class="refer">
              <p class="list"><strong>Please list all of the Hospitals, DME's, and PT's that you refer patients to in the section below</strong></p>
            </div>
            <hr class="blue-line"/>
            <div class="form-check">
              <%= f.check_box :joint_replacement, class: "form-check-input" %>
              <%= f.label "Total Joint Replacement Prehabilitation/Rehabilitation", class: "form-check-label" %>
            </div>
            <hr/>
            <div class="form-check">
              <%= f.check_box :sports_medicine, class: "form-check-input" %>
              <%= f.label "Sports Medicine Prehabilitation/Rehabilitation", class: "form-check-label" %>
            </div>
            <hr/>
            <div class="form-check">
              <%= f.check_box :orthopedic_trauma, class: "form-check-input" %>
              <%= f.label "Orthopedic Trauma Prehabilitation/Rehabilitation", class: "form-check-label" %>
            </div>
            <hr/>
            <div class="form-check">
              <%= f.check_box :non_surgical_orthopedic, class: "form-check-input" %>
              <%= f.label "Non-Surgical Orthopedic Prehabilitation/Rehabilitation", class: "form-check-label" %>
            </div>
            <hr/>
            <div class="form-check">
              <%= f.check_box :spine, class: "form-check-input" %>
              <%= f.label "Spine Prehabilitation/Rehabilitation", class: "form-check-label" %>
            </div>
            <hr/>
            <div class="form-check">
              <div class="flex-other">
                <div>
                  <%= f.check_box :bar %>
                </div>
                <div>
                  <%= f.label "Other:", class: "other-label" %>
                </div>
                <div>
                  <%= f.text_field :other_conditions, class: 'form-control other' %>
                </div>
              </div>
            </div>
        </div>
        <div id="page-2-2">
          <div class="blue">
            <p>NUMBER OF PATIENTS/UNITS PRESCRIBED (Monthly)</p>
          </div>
            <div class="form-product">
              <div id="product">
                <%= f.fields_for :form_products do |product_form| %>
                  <div class="field">
                    <%= f.check_box :foo %>
                    <%= image_tag @products[product_form.index].image, class: "products" %>
                    <%=@products[product_form.index].description%>
                    <span class="amount"><%= product_form.label "# of Units/Month:" %>
                    <%= product_form.text_field :amount %></span>
                    <%= product_form.hidden_field :product_id %>
                    <% if product_form.index < 2 %>
                    <hr/>
                    <% end %>
                  </div>
                <% end %>
              </div>
            </div>
            <hr class="blue-line"/>
            <div class="form-check">
              <%= f.check_box :substitutions, class: "form-check-input" %>
              <%= f.label "No Substitutions", class: "form-check-label" %>
            </div>
            <hr class="blue-line" />
          <div class="field signature">
            <%= f.label "Prescriber Signature:" %>
            <%= f.hidden_field :signature, class: 'signature_pad_input' %>
            <div class="signature_pad text-center">
              <div class="signature_pad_body">
                <canvas></canvas>
              </div>
            </div>
          </div>
          <br/>
          <div class="field">
            <%= f.label "Email:" %>
            <%= f.text_field :email, class: 'form-control' %>
            <%= f.hidden_field :date, value: DateTime.now %>
          </div>
      </div>
    </div>
  </div>


  <div id="page-3">
      <div class="page-header">
        <h5>HOSPITAL/DME INFORMATION</h5>
        <div class="instructions">
        <p><strong>TYPE or PRINT where the prescriptions are to be delivered</strong></p>
        </div>
      </div>
      <div class="section">
          <%= f.fields_for :dme_contacts do |dme_form| %>
          <div class="dme-pt-form">
            <div class="blue">
              <p>HOSPITAL/DME - <%=dme_form.index + 1%></p>
            </div>
              <div class="field">
                <%= dme_form.label "Name:" %>
                <%= dme_form.text_field :name, class: 'form-control' %>
              </div>
              <div class="field">
                <%= dme_form.label "Address:" %>
                <%= dme_form.text_field :street, class: 'form-control' %>
              </div>
              <div>
                <p class="grey">Daytime Contact Information</p>
              </div>
              <div class="field">
                <%= dme_form.label "Phone:" %>
                <%= dme_form.text_field :phone, class: 'form-control' %>
              </div>
              <div class="field">
                <%= dme_form.label "Contact Person:" %>
                <%= dme_form.text_field :primary, class: 'form-control' %>
              </div>
            </div>
          <% end %>
      </div>
  </div>


  <div id="page-4">
      <div class="page-header">
        <h5>PHYSICAL THERAPY INFORMATION</h5>
        <div class="instructions">
        <p><strong>TYPE or PRINT where the prescriptions are to be delivered</strong></p>
        </div>
      </div>
      <div class="section">
          <%= f.fields_for :pt_contacts do |pt_form| %>
          <div class="dme-pt-form">
            <div class="blue">
              <p>PHYSICAL THERAPY - <%=pt_form.index + 1%></p>
            </div>
              <div class="field">
                <%= pt_form.label "Name:" %>
                <%= pt_form.text_field :name, class: 'form-control' %>
              </div>
              <div class="field">
                <%= pt_form.label "Address:" %>
                <%= pt_form.text_field :street, class: 'form-control' %>
              </div>
                <p class="grey">Daytime Contact Information</p>
              <div class="field">
                <%= pt_form.label "Phone:" %>
                <%= pt_form.text_field :phone, class: 'form-control' %>
              </div>
              <div class="field">
                <%= pt_form.label "Contact Person:" %>
                <%= pt_form.text_field :primary, class: 'form-control' %>
              </div>
            </div>
            <% end %>
    </div>
  </div>


  <div class="actions signature_pad_save" id="submit">
    <%= f.submit "Submit", class: "btn btn-primary btn-lg btn-block", id: "submission" %>
  </div>


  <div id="footer">
    <p>COMPANY, LLC. | T: 1 (888) 888-8888 | F: (888) 888-8888 | E: email@email.com</p>
  </div>


<% end %>

app/views/forms/edit.html.erb
<h1> Editing Form </h1>

<%= render 'form', form: @form %>
<%= link_to 'Show', @form %> |
<%= link_to 'Back', forms_path %>

app/views/forms/index.html.erb
<div class="container">
  <div class="index-header">
    <h1>Forms </h1>
    <%= link_to 'New Form', new_form_path, class: " btn btn-success index-btn" %>
    <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "btn btn-danger index-btn log-out") %>
  </div>
  <div class="table-responsive">
    <table class="table table-striped ">
      <thead>
        <tr>
          <th>Form Id</th>
          <th>Surgeon</th>
          <th>Date</th>
          <th>Region</th>
          <th colspan="4"></th>
        </tr>
      </thead>

      <tbody>
        <% @forms.each do |form| %>
          <tr>
            <td id="form-id"><%= form.id %></td>
            <td><%= form.surgeon_contacts.first.name %></td>
            <td><%= form.date&.to_formatted_s(:long) %></td>
            <td><%= form.region %></td>

            <td><%= link_to 'View Form', form, class: "btn btn-info view" %></td>
            <td><%#= link_to 'Destroy', form, method: :delete %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/forms/new.html.erb
  <div class="container">
    <div id="header">
      <div id="logo">
      </div>
      <div>
        <h3> Intent to Prescribe </h3>
      </div>
    </div>
  <div id="info-1">
    <p><strong>Important Information</strong></p>
    <ul>
      <li>This form must be filled out completely by a healthcare professional.</li>
      <li>Intent to prescribe is only available until <strong>12/31/18</strong></li>
      <li>All data collected is confidential and is for manufacturing projections</li>
      <li>This is not a contractual agreement, just an estimate of units to be prescribed</li>
      <li>Healthcare providers completing "Intent to Prescribe" will have priority status upon product launch.</li>
    </ul>
  </div>
  <div id="info-2">
    <p><strong>This form can be filled out and submitted in the following ways: </strong></p>
    <ul>
      <li>Digitally, online, at tommy@tommy.com - (Highly Recommended)</li>
      <li>Filling out the digital PDF and emailing it to pre-orders@tommy.com</li>
      <li>Printing it out and completing it by hand, then faxing it in to: 1-888-888-8888</li>
    </ul>
  </div>
  </div>
  <div class="container">
    <div>
    <%= render 'form', form: @form %>
  </div>
</div>

app/views/forms/show.html.erb
<div class="container">
  <div id="page-1">
      <div class="section">
          <div class="blue">
          <p>SURGEON INFORMATION</p>
          </div>
            <div class="field">
            Surgeon Name: <%= @form&.surgeon_contacts.first.name %>
            </div>
            <hr/>
            <div class="field">
            Surgeon Address: <%= @form&.surgeon_contacts.first.street %>
            </div>
            <hr/>
            <div class="field">
            Surgeon Phone: <%= @form&.surgeon_contacts.first.phone %>
            </div>
            <hr/>
            <div class="field">
            Surgeon Contact Person: <%= @form&.surgeon_contacts.first.primary %>
            </div>
            <hr/>
          <div class="blue">
            <p>REGION</p>
          </div>
            <div class="field">
                <%= @form&.region %>
            </div>
        </div>
  </div>


  <div id="page-2">
    <div class="page-header">
      <h5>SHIPPING INFORMATION</h5>
    </div>
      <div class="section">
        <div id="page-2-1">
            <% if @form.joint_replacement %>
                <div class="field">
                    Joint Replacement
                </div>
            <% end %>
            <hr/>
            <% if @form.sports_medicine %>
                <div class="field">
                    Sports Medicine
                </div>
            <% end %>
            <hr/>
            <% if @form.orthopedic_trauma %>
                <div class="field">
                    Orthopedic Trauma
                </div>
            <% end %>
            <hr/>
            <% if @form.non_surgical_orthopedic %>
                <div class="field">
                    Non-Surgical Orthopedic
                </div>
            <% end %>
            <hr/>
            <% if @form.spine %>
                <div class="field">
                    Spine
                </div>
            <% end %>
            <hr/>
            <% if @form.other_conditions %>
                <div class="field">
                    <%= @form.other_conditions %>
                </div>
            <% end %>
        </div>
        <div id="page-2-2">
          <div class="blue">
            <p>NUMBER OF PATIENTS/UNITS PRESCRIBED (Monthly)</p>
          </div>
            <% @form.form_products[0...-3].each do |product|%>
                <div class="form-product">
                  <% unless product.amount == "" %>
                    <%= product.product.description %>:
                    <strong><%= product&.amount %></strong>
                  <% end %>
                </div>
            <% end %>
            <hr class="blue-line"/>
            <div class="field">
              <% if @form.substitutions %>
                 No Substitions
              <% else %>
                Substitions Acceptable
              <% end %>
            </div>
            <hr class="blue-line" />
          <div class="field signature">
                <%= image_tag @form&.signature %>
            </div>
            <hr/>
          </div>
          <br/>
          <div class="field">
            Email <%= @form&.email %>
            <hr/>
          </div>
          <div class="field">
            Date Signed: <%= @form&.date.to_formatted_s(:long) %>
          </div>
      </div>
  </div>


  <div id="page-3">
      <div class="page-header">
        <h5>SHIPPING INFORMATION</h5>
        <p>TYPE or PRINT where the prescriptions are to be delivered</p>
      </div>
      <div class="section">
        <div class="blue">
          <p>HOSPITAL/DME INFORMATION</p>
        </div>
          <% @form.dme_contacts.each do |contact| %>
            <div class="field">
                Name: <%= contact&.name %>
              <hr/>
            </div>
            <div class="field">
              Address: <%= contact&.street %>
            </div>
            <div>
              <p class="grey">Daytime Contact Information</p>
            </div>
            <div class="field">
                Contact: <%= contact&.phone %>
              <hr/>
            </div>
            <div class="field">
                Contact Person: <%= contact&.name %>
            </div>
            <hr class="blue-line"/>
          <% end %>
      </div>
  </div>


  <div id="page-4">
      <div class="page-header">
        <h5>SHIPPING INFORMATION</h5>
        <p>TYPE or PRINT where the prescriptions are to be delivered</p>
      </div>
      <div class="blue">
        <p>PHYSICAL THERAPY INFORMATION</p>
      </div>
      <div class="section">
          <% @form.pt_contacts.each do |contact|%>
            <div class="field">
                Name: <%= contact&.name %>
              <hr/>
            </div>
            <div class="field">
              Address: <%= contact&.street %>
            </div>
            <div>
              <p class="grey">Daytime Contact Information</p>
            </div>
            <div class="field">
                Contact: <%= contact&.phone %>
              <hr/>
            </div>
            <div class="field">
                Contact Person: <%= contact&.name %>
            </div>
            <hr class="blue-line"/>
            <% end %>
    </div>
  </div>
</div>

app/views/forms/show.pdf.erb
<head>
  <%= wicked_pdf_stylesheet_link_tag "forms" -%>
  <%= wicked_pdf_stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= wicked_pdf_javascript_include_tag "application", "data-turbolinks-track" => true %>
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.2/jquery-ui.js"></script>
</head>
  <div id="page-1">
      <div class="section">
          <div class="blue">
          <p>SURGEON INFORMATION</p>
          </div>
            <div class="field">
            Surgeon Name: <%= @form.surgeon_contacts.first.name %>
            </div>
            <hr/>
            <div class="field">
            Surgeon Address: <%= @form.surgeon_contacts.first.street %>
            </div>
            <hr/>
            <div class="field">
            Surgeon Phone: <%= @form.surgeon_contacts.first.phone %>
            </div>
            <hr/>
            <div class="field">
            Surgeon Contact Person: <%= @form.surgeon_contacts.first.primary %>
            </div>
            <hr/>
          <div class="blue">
            <p>REGION</p>
          </div>
            <div class="field">
                <%= @form.region %>
            </div>
        </div>
  </div>


  <div id="page-2">
    <div class="page-header">
      <h5>SHIPPING INFORMATION</h5>
      <p>TYPE or PRINT where the prescriptions are to be delivered</p>
    </div>
      <div class="section">
        <div id="page-2-1">
            <div class="blue">
              <p>HOSPITAL/DME INFORMATION --- TO BE ADDED</p>
            </div>
            <div class="blue">
              <p>PHYSICAL THERAPY INFORMATION --- TO BE ADDED</p>
            </div>

            <% if @form.joint_replacement %>
                <div class="field">
                    Joint Replacement
                </div>
            <% end %>
            <hr/>
            <% if @form.sports_medicine %>
                <div class="field">
                    Sports Medicine
                </div>
            <% end %>
            <hr/>
            <% if @form.orthopedic_trauma %>
                <div class="field">
                    Orthopedic Trauma
                </div>
            <% end %>
            <hr/>
            <% if @form.spine %>
                <div class="field">
                    Spine
                </div>
            <% end %>
            <hr/>
            <% if @form.other_conditions %>
                <div class="field">
                    <%= @form.other_conditions %>
                </div>
            <% end %>
        </div>
        <div id="page-2-2">
          <div class="blue">
            <p>NUMBER OF PATIENTS/UNITS PRESCRIBED (Monthly)</p>
          </div>

            <% @form.form_products.each do |product|%>
                <div class="form-product">
                <%= product.product.description %>
                <%= product.amount %>
                </div>
            <% end %>

            <hr class="blue-line"/>
            <div class="field">
              <% if @form.substitutions %>
                 Substitions Selected
              <% else %>
                Substitions Not Selected
              <% end %>
            </div>
            <hr class="blue-line" />
          <div class="field signature">
                <%= image_tag @form&.signature %>
            </div>
            <hr/>
          </div>
          <br/>
          <div class="field">
            Email <%= @form.email %>
            <hr/>
          </div>
          <div class="field">
            Date Signed: <%= @form.date.to_formatted_s(:long) %>
          </div>
      </div>
  </div>


  <div id="page-3">
      <div class="page-header">
        <h5>SHIPPING INFORMATION</h5>
        <p>TYPE or PRINT where the prescriptions are to be delivered</p>
      </div>
      <div class="section">
        <div class="blue">
          <p>HOSPITAL/DME INFORMATION</p>
        </div>
          <% @form.dme_contacts.each do |contact| %>
            <div class="field">
                Name: <%= contact.name %>
              <hr/>
            </div>
            <div class="field">
              Address: <%= contact.street %>
            </div>
            <div>
              <p class="grey">Daytime Contact Information</p>
            </div>
            <div class="field">
                Contact: <%= contact.phone %>
              <hr/>
            </div>
            <div class="field">
                Contact Person: <%= contact.name %>
            </div>
            <hr class="blue-line"/>
          <% end %>
      </div>
  </div>


  <div id="page-4">
      <div class="page-header">
        <h5>SHIPPING INFORMATION</h5>
        <p>TYPE or PRINT where the prescriptions are to be delivered</p>
      </div>
      <div class="blue">
        <p>PHYSICAL THERAPY INFORMATION</p>
      </div>
      <div class="section">
          <% @form.pt_contacts.each do |contact|%>
            <div class="field">
                Name: <%= contact.name %>
              <hr/>
            </div>
            <div class="field">
              Address: <%= contact.street %>
            </div>
            <div>
              <p class="grey">Daytime Contact Information</p>
            </div>
            <div class="field">
                Contact: <%= contact.phone %>
              <hr/>
            </div>
            <div class="field">
                Contact Person: <%= contact.name %>
            </div>
            <hr class="blue-line"/>
            <% end %>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Prescription Form</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css">
  </head>

  <body>
    <%= yield %>
    <script src="//code.jquery.com/jquery-1.10.2.js"></script>
    <script src="//code.jquery.com/ui/1.11.2/jquery-ui.js"></script>
  </body>

</html>